//! kosm's sims, and what one is handed when it runs.
//!
//! The module tree below the `Args` is generated by `build.rs` from the
//! directories under `sims/`: a directory with an entry file is a sim, its
//! path under `sims/` is its name, and `SIMS` maps one to the other.
//!
//! The registry in the binary resolves a slash path to a `run`; everything a
//! sim needs to know about the invocation is here, so a sim never reads
//! `std::env::args` itself.

use std::path::{Path, PathBuf};

/// One invocation of one sim.
#[derive(Clone, Debug)]
pub struct Args {
    /// Where every lens output goes. `--out DIR`; `out/` by default.
    pub out: PathBuf,
    /// Whatever followed the sim's path, for the sim to interpret.
    pub rest: Vec<String>,
    /// Whether `--view` was passed: open a window rather than write files.
    pub view: bool,
}

impl Default for Args {
    fn default() -> Self {
        Self { out: PathBuf::from("out"), rest: Vec::new(), view: false }
    }
}

impl Args {
    pub fn out(&self) -> &Path {
        &self.out
    }

    /// The first positional argument the sim was given, if any.
    pub fn positional(&self) -> Option<&str> {
        self.rest.iter().find(|a| !a.starts_with("--")).map(String::as_str)
    }

    /// The value of `--name`, if it was given.
    pub fn value(&self, name: &str) -> Option<&str> {
        let flag = format!("--{name}");
        let i = self.rest.iter().position(|a| *a == flag)?;
        self.rest.get(i + 1).map(String::as_str)
    }

    /// Whether `--name` was given.
    pub fn flag(&self, name: &str) -> bool {
        let flag = format!("--{name}");
        self.rest.iter().any(|a| *a == flag)
    }
}

// so a sim can name `kosm_cli::Args` whether it is compiled here or read as
// a file by an editor
extern crate self as kosm_cli;

include!(concat!(env!("OUT_DIR"), "/registry.rs"));

/// Run the sim at `path` with `rest` as its arguments.
pub fn dispatch(path: &str, rest: &[String]) -> anyhow::Result<()> {
    let Some((_, entry)) = SIMS.iter().find(|(name, _)| *name == path) else {
        anyhow::bail!("no sim at `{path}`; `kosm list` has the tree");
    };
    let mut args = Args::default();
    let mut it = rest.iter();
    while let Some(arg) = it.next() {
        match arg.as_str() {
            "--out" => {
                let dir = it.next().ok_or_else(|| anyhow::anyhow!("--out needs a directory"))?;
                args.out = PathBuf::from(dir);
            }
            "--view" => args.view = true,
            _ => args.rest.push(arg.clone()),
        }
    }
    entry(&args)
}
