//! The filesystem under `sims/` is the registry.
//!
//! Every directory that holds an entry file (`mod.rs` or `main.rs`) is a sim.
//! The top level of `sims/` is declared here, by `#[path]`, at the binary's
//! crate root — so one sim can name another as `crate::<name>`. A directory
//! *inside* a sim is a child module and is declared by its parent's entry
//! file the ordinary way (`pub mod warehouse;` resolves beside it); this
//! script only records that it exists, so `skatepark/warehouse` is a path the
//! registry answers to. Nothing is listed by hand: adding a directory adds a
//! sim.

use std::fmt::Write as _;
use std::fs;
use std::path::{Path, PathBuf};

fn main() {
    let sims = PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("../../sims");
    println!("cargo:rerun-if-changed={}", sims.display());

    let mut mods = String::new();
    let mut table = Vec::new();
    for (dir, name) in dirs(&sims) {
        let ident = name.replace('-', "_");
        let entry = dir.join(entry_file(&dir).unwrap());
        let _ = writeln!(mods, "#[path = {:?}]\npub mod {ident};", entry.display().to_string());
        collect(&dir, &name, &ident, &mut table);
    }
    table.sort();

    let mut out = String::from("// generated by build.rs; the tree under sims/ is the source\n");
    out.push_str(&mods);
    out.push_str(
        "\n/// Every sim, keyed by its path under `sims/`.\n\
         pub const SIMS: &[(&str, fn(&kosm_cli::Args) -> anyhow::Result<()>)] = &[\n",
    );
    for (path, module) in &table {
        let _ = writeln!(out, "    ({path:?}, {module}::run),");
    }
    out.push_str("];\n");

    let dst = PathBuf::from(std::env::var("OUT_DIR").unwrap()).join("registry.rs");
    fs::write(dst, out).unwrap();
}

/// `(path under sims/, module path)` for this sim and every sim nested in it.
fn collect(dir: &Path, path: &str, module: &str, table: &mut Vec<(String, String)>) {
    println!("cargo:rerun-if-changed={}", dir.display());
    table.push((path.to_owned(), module.to_owned()));
    for (child, name) in dirs(dir) {
        let ident = name.replace('-', "_");
        collect(&child, &format!("{path}/{name}"), &format!("{module}::{ident}"), table);
    }
}

/// The sim directories directly inside `dir`, sorted, skipping dotfiles.
fn dirs(dir: &Path) -> Vec<(PathBuf, String)> {
    let Ok(entries) = fs::read_dir(dir) else { return Vec::new() };
    let mut out: Vec<(PathBuf, String)> = entries
        .filter_map(|e| e.ok())
        .map(|e| e.path())
        .filter(|p| p.is_dir())
        .filter_map(|p| {
            let name = p.file_name()?.to_str()?.to_owned();
            (!name.starts_with('.') && entry_file(&p).is_some())
                .then_some((p, name))
        })
        .collect();
    out.sort();
    out
}

fn entry_file(dir: &Path) -> Option<&'static str> {
    ["mod.rs", "main.rs"].into_iter().find(|n| dir.join(n).is_file())
}
